### ISSUE TITLE
请教IDEA terminal 多余空行问题

### ISSUE THREAD

**Issue by xiaozhaolhg** [xiaoxiunique/tool-tips#1]
你好, 有个问题请教一下.
我在IDEA的terminal里边, 不管是用默认的cmd, 还是改用git-bash的bash, 命令执行完之后, 都会有多余的一个空行, 看起来很不舒服, 请问这个能去掉吗? 谢谢! 

![image](https://user-images.githubusercontent.com/16432304/65211440-4f010e00-dad1-11e9-9b34-87fea03cc4bb.png)

**Comment by xiaoxiunique** [comment]
:smile::smile::smile::smile:  以前重来没注意过这个问题, 没有看到相关的设置, 不过个人感觉有空格还挺好看的呢  :bulb::bulb::bulb::bulb:
