### ISSUE TITLE
请教一下 column selection mode 快捷键问题

### ISSUE THREAD

**Issue by rainbow702** [xiaoxiunique/tool-tips#13]
你好

我在你的 [多光标操作集锦](https://atips.cn/idea/IDEA%20%E5%A4%9A%E5%85%89%E6%A0%87%E6%93%8D%E4%BD%9C%E9%9B%86%E9%94%A6.html) 这篇文章中看到有关于 **数列光标** 的说明，里面写的快捷写是 `Alt+按住鼠标左键拖动`。

我以前在使用 2017 版的 IDEA 的时候，的确也是这个快捷键，但是现在换成了 2019.3.3 版之后，这个快捷键就用不了了。

网上查了一下，发现，不管是 官网 还是 stackoverflow 上，都说快捷键是 `Shift+Alt+Insert`：
* https://www.jetbrains.com/help/rider/Multicursor.html?keymap=_default#column_selection
* https://stackoverflow.com/questions/26386079/intellij-column-selection-using-cursor-keys/39532659

在 stackoverflow 的回复中，有人指出可以通过 **按住鼠标中键拖动** 来实现这个目的，我试了下，的确可以，但是始终感觉没有 `Alt+按住鼠标左键拖动` 这个来的好用。

所以，想请教一下，关于这个快捷现在能通过什么样的方法设置成 `Alt+按住鼠标左键拖动` 呢？
PS：IDEA 的 `Settings | Keymap` 无法实现这个目的。

**Comment by xiaoxiunique** [comment]
我这边实验了一下，我现在的版本是 2019.3 是可以用这个功能的。但是我的同版本的 **WebStorm** 不能这样使用。

**Comment by xiaoxiunique** [comment]
然后 WebStorm 里面的快捷键是 **Shift + Alt**  -> 按住鼠标拖动，恕我直言，我试用了一下 `Shift + Alt + Insert` ，真的难用。。。

**Comment by xiaoxiunique** [comment]
你可以先用一下 `Shift + Alt ` 的方式行不

**Comment by rainbow702** [comment]
我是在 CentOS 7.7 中安装的 IDEA ， 如果你的行的话，有可能我的宿主机有问题吧，郁闷( ˇˍˇ )
